services:
  app:
    build:
      context: .
    volumes:
      - ./go.mod:/code/go.mod
      - ./go.sum:/code/go.sum
      - ./.air.toml:/code/.air.toml
      - ./cmd:/code/cmd
      - ./internal:/code/internal
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-codelibrary}
      COOKIE_SECRET: "9oXbMuw9dbUCFNQHc65De/LBQd4cML4WV/R6NTf1fg8="
    command: air
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - codelibrary
  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=codelibrary
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - codelibrary
  ui:
    build:
      context: codelibrary-ui
    volumes:
      - ./codelibrary-ui/tsconfig.json:/code/tsconfig.json
      - ./codelibrary-ui/webpack.config.ts:/code/webpack.config.ts
      - ./codelibrary-ui/src:/code/src
      - ./codelibrary-ui/public:/code/public
    command: yarn run dev-server
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - codelibrary

volumes:
  pgdata:

networks:
  codelibrary:
    driver: bridge
